# Generated by Django 4.2.4 on 2023-08-29 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 21, 26, 46, 542068)),
        ),
    ]
