# Generated by Django 4.2.4 on 2023-08-29 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 21, 31, 48, 474898)),
        ),
    ]
